<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>click_tick</name>
   <tag></tag>
   <elementGuidId>fd4317ae-6f07-4e1f-8e25-5c1721674339</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//i</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>i</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>material-icons toggle-completed-checkbox</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/app-root[1]/main[1]/todo-list[1]/div[@class=&quot;todo-content&quot;]/ul[@class=&quot;todo-list&quot;]/li[1]/div[@class=&quot;todo-row&quot;]/a[@class=&quot;todo-completed&quot;]/i[@class=&quot;material-icons toggle-completed-checkbox&quot;]</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//i</value>
   </webElementXpaths>
</WebElementEntity>
